---
kind: pipeline
type: exec
name: docker-system-prune

platform:
  os: linux
  arch: amd64

steps:
- name: integration-tests
  commands:
  - docker system prune -f

---
kind: signature
hmac: bdc2684e182cf00ebf7a8a2e7971884e5ff9ee193d16398aec745bcd1260cf6f

...
