---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: Tests
  commands:
  - export NIX_REMOTE=daemon
  - export PATH="/nix/var/nix/profiles/default/bin/:$PATH"
  - . /usr/local/etc/profile.d/nix.sh
  - . /opt/intel/sgxsdk/sgxsdk/environment
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  - nix-channel --update
  - nix-shell drone.nix --run "./run-integration-tests.sh"

...