---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: Environment
  commands:
  - export NIX_REMOTE=daemon
  - echo $PATH
  - . /usr/local/etc/profile.d/nix.sh
  - echo $PATH
  - . /opt/intel/sgxsdk/sgxsdk/environment
  - echo $PATH
  - nix-shell drone.nix

- name: Build
  commands:
  - cd integration-tests
  - ./prepare.sh
  - . ./env.sh
  - docker-compose up -d
  - sleep 25
  - docker ps
  - docker-compose logs -t --tail="all"

- name: Preliminary tests
  commands:
  - ./run-test.sh

- name: Integration tests
  commands:
  - cd client-rpc
  - yarn
  - yarn test
  - docker ps

...