---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: install-docker-compose
  commands:
  - mkdir bin
  - export PATH="$PATH:$PWD/bin"
  - curl -sSL "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o bin/docker-compose
  - chmod +x bin/docker-compose
  - export NIX_REMOTE=daemon
  - export PATH="$PATH:/nix/var/nix/profiles/default/bin/"
  - . /usr/local/etc/profile.d/nix.sh
  - . /opt/intel/sgxsdk/sgxsdk/environment
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  - nix-channel --update
  - nix-shell drone.nix --run "./run-integration-tests.sh"

...