---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: Environment and dependencies
  commands:
  - export NIX_REMOTE=daemon
  - echo $PATH
  - . /usr/local/etc/profile.d/nix.sh
  - echo $PATH
  - nix-shell drone.nix
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - export LD_LIBRARY_PATH=$HOME/lib
  - export LIBRARY_PATH=$HOME/lib
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - . /opt/intel/sgxsdk/sgxsdk/environment

- name: Build
  commands:
  - cd integration-tests
  - ./prepare.sh
  - . ./env.sh
  - docker-compose up -d
  - sleep 25
  - docker ps
  - docker-compose logs -t --tail="all"

- name: Preliminary tests
  commands:
  - ./run-test.sh

- name: Integration tests
  commands:
  - cd client-rpc
  - yarn
  - yarn test
  - docker ps

...